import Foundation

let basicSymbols: SymbolCollection = SymbolCollection(title: "Basic", symbols: [
    Symbol(glyph: "∎", name: "End of Proof"),
    Symbol(glyph: "ℕ", name: "Double-struck Capital N (Naturals)"),
    Symbol(glyph: "ℤ", name: "Double-struck Capital Z (Integers)"),
    Symbol(glyph: "ℚ", name: "Double-struck Capital Q (Rationals)"),
    Symbol(glyph: "ℝ", name: "Double-struck Capital R (Reals)"),
    Symbol(glyph: "ℂ", name: "Double-struck Capital C (Complex)"),
    Symbol(glyph: "ℍ", name: "Double-struck Capital H (Quaternions)"),
    Symbol(glyph: "𝔻", name: "Double-struck Capital D"),
    Symbol(glyph: "∞", name: "Infinity"),
    Symbol(glyph: "≡", name: "Identical to"),
    Symbol(glyph: "=", name: "Equals Sign"),
    Symbol(glyph: "≠", name: "Not Equal To"),
    Symbol(glyph: "≈", name: "Almost Equal To"),
    Symbol(glyph: "∅", name: "Empty Set"),
    Symbol(glyph: "⊥", name: "Up Tack/Bottom Element/Nullity (Wheel Theory)"),
    Symbol(glyph: "∴", name: "Therefore"),
    Symbol(glyph: "∵", name: "Because"),
    Symbol(glyph: "÷", name: "Division Sign"),
    Symbol(glyph: "π", name: "Pi"),
    Symbol(glyph: "∠", name: "Angle"),
    Symbol(glyph: "∇", name: "Nabla"),
    Symbol(glyph: "∂", name: "Partial Differential"),
    Symbol(glyph: "∀", name: "For All"),
    Symbol(glyph: "∃", name: "Exists"),
    Symbol(glyph: "⇒", name: "Implies"),
    Symbol(glyph: "⇔", name: "Equivalent"),
    Symbol(glyph: "¬", name: "Negation"),
    Symbol(glyph: "∝", name: "Proportional To"),
    Symbol(glyph: "≤", name: "Less Than or Equal To"),
    Symbol(glyph: "≥", name: "Greater Than or Equal To")
])
